- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: "3.10"

- name: Install Cog
  run: |
    curl -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64 -o cog
    chmod +x cog
    sudo mv cog /usr/local/bin/cog

- name: Install Dependencies
  run: pip install -r requirements.txt || true

- name: Validate Cog Setup
  run: cog check

- name: Authenticate with Replicate
  run: echo "${{ secrets.REPLICATE_TOKEN }}" | cog login --token-stdin

- name: Push model to Replicate
  run: cog push r8.im/glenihenacho/pro-grounded-sam
